name: Deploy and Run Commands on EC2

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Run commands on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-65-2-166-249.ap-south-1.compute.amazonaws.com << 'EOF'
        cd generative-ai-docs/examples/gemini/python/docs-agent
        export GOOGLE_API_KEY=AIzaSyCKjKDOD4K2TK4czP3EvcCBTGd-q53vw_8
        tmux kill-server
        tmux new-session -d 'poetry shell && agent chatbot'
        EOF
